'@notify/api-service':
  - apps/api/**/*
'@notify/worker':
  - apps/worker/**/*
'@notify/dashboard':
  - apps/dashboard/**/*
'@notify/ws':
  - apps/ws/**/*
'@notify/inbound-mail':
  - apps/inbound-mail/**/*
'@notify/webhook':
  - apps/webhook/**/*
'@novu/thalamus-observer':
  - enterprise/workers/thalamus-observer/**/*
'@notify/dal':
  - libs/dal/**/*
'@notify/shared':
  - packages/shared/**/*
'providers':
  - providers/**/*
'CI/CD':
  - .github/**/*
'docker':
  - docker/**/*
'scripts':
  - scripts/**/*
